### ISSUE TITLE
insufficient hooks explanations 

### ISSUE THREAD

**Issue by yairEO** [zakariaharti/react-hookedup#2]
for example, how is `useInterval` better than normal setInterval? what is the use case?

**Comment by omnidan** [comment]
@yairEO there are several problems with using `setInterval` directly. For example, it will start a new timer every time the component re-renders (when any props or hook/state values change). This can cause bugs and also memory leaks if we do not clear the timers first. We also need to clear the timers before the component unmounts.

The `useInterval` and `useTimeout` hooks deal with these problems by using an effect hook with a cleanup function.
